kind: Service
apiVersion: v1
metadata:
  name: demo-backend-service
spec:
  selector:
    app: demo-backend
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  labels:
    app: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      volumes:
      - name: db
        emptyDir:
          medium: Memory
      initContainers:
      - name: migrate
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        args:
          - migrate
        volumeMounts:
        - name: db
          mountPath: /app/db
      containers:
      - name: backend
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        args:
          - runserver
          - 0.0.0.0:80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: db
          mountPath: /app/db
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: backend-ingress
spec:
  rules:
  - host: ${CICD_GIT_BRANCH}.demo.p1b.us
    http:
      paths:
      - path: /api/*
        backend:
          serviceName: demo-backend-service
          servicePort: 80
